### ISSUE TITLE
Request: allow disabling of Red Canary banner on binary execution

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [redcanaryco/chain-reactor#16]
When executing the created binary, a massive Red Canary banner is output every time, taking up well over half my screen on a large monitor. It would be nice if we could have the option during binary creation to disable this to save screen space on execution.

**Comment by rc-grey** [comment]
@Marshall-Hallenbeck How does that look to you? Pull-request linked.

**Comment by Marshall-Hallenbeck** [comment]
@rc-grey Looks great, thanks! Just tested it as well.
